=== AdHouen/RessourcesAFPA/Xavier/20220930_9_Exemple_FeuilleDeStyleDeTransformation_et_DTD/mailing-list_1.dtd
<!ELEMENT mailing-list ((adresse)*)>
<!ELEMENT adresse (nom,(email)*)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email statut (perso|prof) "perso" >

=== AdHouen/RessourcesAFPA/Xavier/20220930_9_Exemple_FeuilleDeStyleDeTransformation_et_DTD/mailing-list2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "mailing-list_1.dtd">
<?xml-stylesheet type="text/xsl" href="transformation_html.xsl"?>
<mailing-list>
	<adresse>
		<nom>Carthy</nom>
		<email statut="perso">carthy@mail.fr</email>
		<email statut="prof">cart@afpa.fr</email>
	</adresse>
	<adresse>
		<nom>Anthony</nom>
		<email statut="perso">Anthony@free.fr</email>
	</adresse>
</mailing-list>
